version: "3.8"

services:
  postgres:
    image: postgres:14-bullseye
    container_name: bm-api-postgres-container
    restart: unless-stopped
    volumes:
      - bm-pgdata:/var/lib/postgresql/data
    networks:
      - bm-api-network
    env_file: ./config/.env

  redis:
    image: redis:7-bullseye
    container_name: bm-api-redis-container
    volumes:
      - bm-redisdata:/data
    networks:
      - bm-api-network
    env_file: ./config/.env

  web:
    build:
      context: src/
      dockerfile: Dockerfile
    container_name: bm-api-django-container
    restart: "unless-stopped"
    stop_grace_period: "5s"
    volumes:
      - ./src:/usr/src/app
      - bm-django-static:/var/www/django/static
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    networks:
      - bm-api-network
      - bm-api-proxy-network
    env_file:
      - ./config/.env

networks:
  bm-api-proxy-network:
    name: bm-api-proxy-network
  bm-api-network:

volumes:
  bm-pgdata:
  bm-redisdata:
  bm-django-static:
