version: "3.9"

services:
  postgres:
    image: postgres:13-alpine
    container_name: bm-api-postgres-container
    restart: unless-stopped
    volumes:
      - bm-pgdata:/var/lib/postgresql/data
    networks:
      - bm-api-network
    env_file: ./config/.env

  web:
    build:
      context: src/
      dockerfile: Dockerfile
    container_name: bm-api-django-container
    restart: "unless-stopped"
    stop_grace_period: "5s"
    volumes:
      - ./src:/usr/src/app
      - bm-django-static:/var/www/django/static
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - bm-api-network
      - bm-api-proxy-network
    env_file: ./config/.env

networks:
  bm-api-proxy-network:
    name: bm-api-proxy-network
  bm-api-network:

volumes:
  bm-pgdata:
  bm-django-static:
