# Generated by Django 3.2.13 on 2022-05-09 00:34

from django.db import migrations, models
import localflavor.br.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(editable=False, verbose_name='Última atualização em')),
                ('name', models.CharField(max_length=128, verbose_name='Nome')),
                ('cnpj', localflavor.br.models.BRCNPJField(max_length=18, verbose_name='CNPJ')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ('-id',),
            },
        ),
    ]
