# Generated by Django 3.2.13 on 2022-05-09 00:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nome')),
                ('description', models.TextField(verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Itens',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Posição')),
                ('price', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Preço')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantidade no Estoque')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='items.item')),
            ],
            options={
                'verbose_name': 'Estoque',
                'verbose_name_plural': 'Estoques',
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(editable=False, verbose_name='Última atualização em')),
                ('date', models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='Hora da Venda')),
                ('is_paid', models.BooleanField(default=True, verbose_name='Venda Paga')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Desconto')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Valor Pago')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
                'ordering': ('-created_at',),
            },
        ),
    ]
