name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Heroku Container registry
        working-directory: "./src"
        run: heroku container:login
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Build and push
        working-directory: "./src"
        run: heroku container:push -a yn-bm web
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Release
        working-directory: "./src"
        run: heroku container:release -a yn-bm web
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
